name: Build with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew 
        ./gradlew build
           
    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        path: build/libs/*.jar
        compression-level: 0
